### ISSUE TITLE
Resampling and other Audio utilities - focus work at the RustAudio/sample crate?

### ISSUE THREAD

**Issue by mitchmindtree** [RustAudio/audrey#11]
This is a follow up to @est31's idea of providing an audio utilities crate.

@est31 I started the [rustaudio/sample](https://github.com/RustAudio/sample) crate a while ago to fulfill this purpose - I'd love to get your thoughts on it!

`audio` already uses it to handle target sample format conversion in the `read::Samples` and `read::Frames` iterators. `sample` supports linear and sinc interpolation for resampling at the moment and I'd be happy to see more kinds of resampling supported if need be. It is dependency-less and only depends on rust's core library. It has a thorough suite of tests for conversions, fairly extensive documentation and I've used it in the majority of my personal audio-related rust projects with success so far. It would be great to get your thoughts on it if you get a chance 😸

**Comment by mitchmindtree** [comment]
I should add - having the `sample` crate reach its current usability and knowing that it had the sample format, rate conversion and frame handling functionality that would be required is part of the reason why I felt comfortable in finally attempting to start an audio crate like this.

**Comment by est31** [comment]
Oh there is already the `sample` crate. Very nice. I'll give it a look tomorrow.

**Comment by est31** [comment]
So it took a bit more time than one day for me to look at the sample crate :laughing: . It looks really awesome! I think you are right, we should focus on the `sample` crate :). I'll close this as the point is resolved.
