### ISSUE TITLE
0.2 release

### ISSUE THREAD

**Issue by est31** [RustAudio/audrey#18]
@mitchmindtree could we get a 0.2 release?

Also, can you add me as owner of the crate on crates.io? Thanks :)

**Comment by est31** [comment]
I'd love to have a 0.2 release so that I can update the deepspeech-rs example to use audrey to convert any samples to a format that the deepspeech code needs/wants.

**Comment by mitchmindtree** [comment]
Oh absolutely! I just added the `github:RustAudio:owners` group as an owner on crates.io and published 0.2 #19 :+1:

**Comment by est31** [comment]
Giving team access is even better, as it allows nicer management :). I have created a team `github:rustaudio:cratesio-publish` that can manage this, focussed on this task so that we can give others the rights to publish crates in the future as well if we want/need to.

I have given access for the team to the crates I control. If you want, you can do this too! This would improve the bus factor :).

**Comment by est31** [comment]
Also, I have published a new release of the deepspeech-rs crate. Thank you!
