### ISSUE TITLE
Crate name - Host on crates.io as `audio` or something else?

### ISSUE THREAD

**Issue by mitchmindtree** [RustAudio/audrey#2]
I thought `audio` could be a good name for the crate, as I kind of see it as an audio equivalent of the `image` crate.

It seems the `audio` name is currently reserved, though the crate looks to be empty or at least inactive. Perhaps we can contact the owner to see if they would be at all interested in transferring the crate name to us.

**Comment by mitchmindtree** [comment]
Either way, we will first need to either wait for `lewton` to publish `0.5.0` or switch `lewton` to `0.4.1` and import the `ogg` crate before we can publish due to RustAudio/lewton#13.

**Comment by mitchmindtree** [comment]
Hi @mahkoh, I hope you don't mind me contacting you here! I would have emailed you only I couldn't find any public addresses. Feel free to disregard this if you'd prefer to!

I wanted to inquire whether or not you were still using (or have plans for) the [`audio` crate](https://crates.io/crates/audio) on crates.io? If so, no problems at all, I'd be happy to find another name if necessary :+1: If however you do not, I was wondering if you would consider transferring ownership of the crate to the [RustAudio](https://github.com/RustAudio) organisation so that we may use it to publish the crate hosted at this repository? I thought the name might be a good fit for the reason I mentioned in the parent comment. Also, in case you had something similar in mind for the crate I'd be happy to invite you to the org!

**Comment by est31** [comment]
I don't want my crate to be a blocker. I'm ready to release a 0.5.0 version with only this change and put subsequent changes into the upcoming 0.6.0 version if its required.

**Comment by mitchmindtree** [comment]
@est31 no point rushing it until we decide on a name yet :)

As a possible alternative in the case that @mahkoh does not respond or does not want to release the crate, I thought `audrey` might be nice? I think it's a pretty name, concise, memorable and starts with "aud" for audio?

**Comment by mitchmindtree** [comment]
Ok, no word from @mahkoh so I think it might be time to settle on something else.

I'll probably go ahead with `audrey` within the next few days unless anyone would like to recommend other preferences!

**Comment by est31** [comment]
Alternative name suggestion: "hear".

**Comment by cseale** [comment]
`audrey` is a really nice suggestion I think. Kind of memorable.

**Comment by mitchmindtree** [comment]
OK I'm going to just publish this as `audrey` for now - can always re-publish in the future if the anyone has any great desire to do so!
