### ISSUE TITLE
Documentation + Wasm

### ISSUE THREAD

**Issue by nuthinking** [RustAudio/audrey#20]
This library seems incredibly useful to do audio file conversion in a web client through Wasm.

Is there some documentation about this library somewhere?

In particular, I would need a way to convert a WAV buffer to AAC to pass it back to JavaScript.

Thanks!

**Comment by est31** [comment]
Hi @nuthinking and thanks for your interest in the audrey crate!

Right now, it is focused on decoding only as in taking compressed streams and outputting generated WAV, so the other way round. Encoding support is not implemented.

As for AAC encoders, it seems there are no non-proprietary licensed implementations that allow to be bundled with proprietary code. However, there are very fine opus encoders. So I'd suggest you try one of the wasm opus encoders out there:

* https://github.com/AnthumChris/opus-stream-decoder 
* https://github.com/chris-rudmin/opus-recorder
