### ISSUE TITLE
Writing

### ISSUE THREAD

**Issue by schell** [RustAudio/audrey#26]
It's not obvious that this library does encoding and writing of any audio formats. Is this on the roadmap? Maybe in a branch?

**Comment by est31** [comment]
Yes, it's not supported. See the supported formats table in the README.

**Comment by schell** [comment]
Not supported and out of scope, ie this library will never do encoding?

I ask simply because of the readme/description: 
> A crate to simplify reading, writing and converting between a range of audio formats.

**Comment by est31** [comment]
It's not out of scope, maybe one day it will. In general, I think our goal was to be the `image` crate for audio.
