### ISSUE TITLE
Support ALAC format decoding via `alac` crate?

### ISSUE THREAD

**Issue by mitchmindtree** [RustAudio/audrey#5]
Here's the [alac](https://crates.io/crates/alac) crate.

**Comment by est31** [comment]
Seems its only a decoder for the actual audio codec, with support for no containers. If we wanted to use it we'd require support for the [CAF container](https://en.wikipedia.org/wiki/Core_Audio_Format) format (where ALAC is usually inside). Dunno if its on crates.io but audio container formats are quite easy so we could write our own if there is none.

**Comment by est31** [comment]
Seems I was wrong. While CAF does sometimes appear in the CAF container, it most often appears in the MP4 container. I've filed an issue for it: https://github.com/mozilla/mp4parse-rust/issues/57

I've already started work though on a CAF decoder, won't abort it.

**Comment by est31** [comment]
I've published it here: https://github.com/RustAudio/caf

Its not polished yet, so its not ready for a crates.io upload. It supports reading CAF/ALAC files already.

Currently I'm trying to get it integrated into the audio crate.
