### ISSUE TITLE
MP3 decoder

### ISSUE THREAD

**Issue by est31** [RustAudio/audrey#6]
Would be cool to have a pure rust MP3 decoder that's permissively licensed. Couldn't find anything on crates.io, so we'd have to write our own.

While there are quite some free software decoders written in C, most of them are copylefted (LGPL or GPL).

These are the only non copyleft implementations I could find:

* fluendo decoder (available by `svn co`'ing [this URL](https://core.fluendo.com/gstreamer/svn/trunk/gst-fluendo-mp3) ) => claims to be MIT licensed, however it contains code from the ISO mp3 distribution 10, which is non free, so the MIT claim is dubious...
* http://hackage.haskell.org/package/mp3decoder => BSD like license
* Writeup about some parts of the codec: http://blog.bjrn.se/2008/10/lets-build-mp3-decoder.html

This is a big list of decoders available (most of them are either non free or copyleft): http://www.mp3-tech.org/programmer/decoding.html

I'd say we should port the haskell decoder to rust. Any volunteers?

**Comment by est31** [comment]
found another non GPL-d mp3 decoder: https://android.googlesource.com/platform/frameworks/av/+/master/media/libstagefright/codecs/mp3dec/

**Comment by Aceeri** [comment]
Other useful resources I've found:

https://bitbucket.org/portalfire/pymp3/src/c6a4df75a660021b90e3bb2da2d418aed22ea9bd/pyMP3.py?at=default&fileviewer=file-view-default (Python mp3 decoder)

https://www.mp3-tech.org/programmer/docs/mp3_theory.pdf (Overview on the mp3 format)

**Comment by est31** [comment]
It seems that @blanham is interested in creating a decoder as well...

**Comment by blanham** [comment]
Oh hi! I started researching an mp3 decoder but didn't get very far due to personal stuff. My long term plan was to have it be a decoder and encoder, and maybe have ID3 decoding built-in (I know there are a few existing ID3 tag libraries, but I think it might make sense to include it with the encoder/decoder) I might be able to dedicate some time to restarting work now, and would definitely be open to adding it to the org. I was going to license it under 2BSD or MIT, so I think that will work well with your goals. I'll see what I can do, and if I haven't made any progress in the next month I can turn the `mp3` crate over to RustAudio at the least. I idle on IRC as ChickeNES, feel free to hit me up there, though it might take me a while to respond.

**Comment by est31** [comment]
@blanham that sounds really great!

> I haven't made any progress in the next month I can turn the mp3 crate over to RustAudio

Its a great idea to give us access. Very much appreciated! All of us are doing this in our free time, and I'm taking months to develop a decoder myself, so if its not ready in a month don't give up on it just yet :). I've also sent you an invite to the org.

**Comment by est31** [comment]
It seems there hasn't been much progress on this issue lately. @blanham how far have you got? @bemeurer has decided to bring new activity behind this. We have created a repo here and there is a tracking issue for future work https://github.com/RustAudio/mp3/issues/1 . If you have anything substantial, can you publish it? We will decide on whose implementation (yours or @Aceeri 's) we are going to base it on. In any case, we'd be glad to get access to the mp3 crate name :). You can do `cargo owner --add` from the directory of your mp3 decoder repository. Thank you!

**Comment by lieff** [comment]
@est31 Now crates.io have such package https://crates.io/crates/minimp3

**Comment by blanham** [comment]
Hi everyone, missed the notification emails on this, sorry about that. Let me dig up my old code and see how far along I was, can get back to y'all this weekend. At the very least I'd love to be involved in some way!

**Comment by est31** [comment]
@blanham kind reminder, do you have a base to share that we can start work on? Then you will be involved :).

**Comment by mainrs** [comment]
btw, minimp3 looks to be licensed under the Creative Commons Zero license, so it should be compatible :smile:

**Comment by est31** [comment]
@SirWindfield yes, using it as reference and maybe even porting parts of it to Rust is definitely on the radar.

We also have this roadmap issue for the project: https://github.com/RustAudio/mp3/issues/1

**Comment by est31** [comment]
Closing in favour of https://github.com/RustAudio/mp3/issues/1
